name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  dio: ^5.4.1
  http: ^1.2.1
  fluttertoast: ^8.2.4
  flutter_profile_picture: ^2.0.0
  toggle_switch: ^2.1.0
  email_validator: ^2.1.17
  flutter_svg: ^2.0.10+1
  another_flutter_splash_screen: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  salomon_bottom_bar: ^3.3.2
  infinite_scroll_pagination: ^4.0.0
  google_mobile_ads: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo_evt_android.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_evt_android.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_evt.png
    - assets/images/avatar.png
    - assets/images/Profile Image.png
    - assets/images/profile.png
    - assets/images/Bell.png
    - assets/images/setting.png
    - assets/images/logout.png
    - assets/images/logo_evt_android.png
    - assets/images/cancel.png
    - assets/images/correct.png
    - assets/gif/search.gif
    - assets/images/not_found.jpg

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSansThai-Medium.ttf
        - asset: assets/fonts/IBMPlexSansThai-Bold.ttf
        - asset: assets/fonts/IBMPlexSansThai-ExtraLight.ttf         
        - asset: assets/fonts/IBMPlexSansThai-Light.ttf         
        - asset: assets/fonts/IBMPlexSansThai-Regular.ttf          
        - asset: assets/fonts/IBMPlexSansThai-SemiBold.ttf
        - asset: assets/fonts/IBMPlexSansThai-Thin.ttf